// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFzSEaJlJZYzvU6XPD2suuU4_KqEROIqY',
    appId: '1:79838517894:web:fb7f596f64659206c08f07',
    messagingSenderId: '79838517894',
    projectId: 'lilia-app-d8f6f',
    authDomain: 'lilia-app-d8f6f.firebaseapp.com',
    storageBucket: 'lilia-app-d8f6f.firebasestorage.app',
    measurementId: 'G-NRZQ03CQ6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTMt0Gv2t0D6kUycVVhB4tgWn-IMQa2Y',
    appId: '1:79838517894:android:635d1cc397fe3d61c08f07',
    messagingSenderId: '79838517894',
    projectId: 'lilia-app-d8f6f',
    storageBucket: 'lilia-app-d8f6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6a-vecaUYvvMviHFmxso4k8CcDC1GvU',
    appId: '1:79838517894:ios:299f829e9ed19b05c08f07',
    messagingSenderId: '79838517894',
    projectId: 'lilia-app-d8f6f',
    storageBucket: 'lilia-app-d8f6f.firebasestorage.app',
    iosBundleId: 'com.dreesis.lilia.liliaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA6a-vecaUYvvMviHFmxso4k8CcDC1GvU',
    appId: '1:79838517894:ios:299f829e9ed19b05c08f07',
    messagingSenderId: '79838517894',
    projectId: 'lilia-app-d8f6f',
    storageBucket: 'lilia-app-d8f6f.firebasestorage.app',
    iosBundleId: 'com.dreesis.lilia.liliaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFzSEaJlJZYzvU6XPD2suuU4_KqEROIqY',
    appId: '1:79838517894:web:18c81068e7ffb655c08f07',
    messagingSenderId: '79838517894',
    projectId: 'lilia-app-d8f6f',
    authDomain: 'lilia-app-d8f6f.firebaseapp.com',
    storageBucket: 'lilia-app-d8f6f.firebasestorage.app',
    measurementId: 'G-6ERTC4CBZC',
  );
}
